# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Rails Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - name: Run Elasticsearch
      uses: perfect-ruby-on-rails/elasticsearch-with-plugins-action@v1
      with:
        stack-version: 7.6.0
        plugins: |
          analysis-kuromoji
    - name: Build and test
      env:
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libsqlite3-dev
        bundle install --jobs 4 --retry 3
        rails db:create
        rails db:migrate
        yarn install
        rails test
        rails test:system
